# Generated by Django 3.1.5 on 2021-02-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('dateline', models.DateField()),
                ('now_date', models.DateField(auto_now=True)),
                ('priority', models.CharField(choices=[('denger', 'high'), ('primary', 'low')], max_length=50)),
            ],
        ),
    ]
